channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - ipython==8.10.0
  - plotly==5.13.0
  - prophet==1.1.2
  - scikit-learn==1.2.1
name: mlflow-env
